version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    phpfpm:
        build: ./docker/php-fpm
        expose:
            - "9000"
        volumes:
            - ./app/symfony:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        links:
            - db
    phpratchet:
        build: ./docker/php-ratchet
        expose:
            - "8080"
        volumes:
            - ./app/ratchet:/var/ratchet
        links:
            - db
    nginx:
        build: ./docker/nginx
        ports:
            - "80:80"
        links:
            - phpfpm
        volumes_from:
            - phpfpm
        volumes:
            - ./logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./docker/elk/logstash:/etc/logstash
            - ./docker/elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - phpfpm
            - nginx
